let strip = neopixel.create(DigitalPin.P2, 60, NeoPixelMode.RGB)
basic.forever(function () {
    while (true) {
        strip.showColor(neopixel.colors(NeoPixelColors.Red))
        strip.show()
        basic.pause(1000)
        strip.showColor(neopixel.colors(NeoPixelColors.Orange))
        strip.show()
        basic.pause(1000)
        strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
        strip.show()
        basic.pause(1000)
        strip.showColor(neopixel.colors(NeoPixelColors.Green))
        strip.show()
        basic.pause(1000)
        strip.showColor(neopixel.colors(NeoPixelColors.Blue))
        strip.show()
        basic.pause(1000)
        strip.showColor(neopixel.colors(NeoPixelColors.Indigo))
        strip.show()
        basic.pause(1000)
        strip.showColor(neopixel.colors(NeoPixelColors.Purple))
        strip.show()
        basic.pause(1000)
        strip.showColor(neopixel.colors(NeoPixelColors.Violet))
        strip.show()
        basic.pause(1000)
    }
})
